### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by henriksjostrom** [karpathy/svmjs#4]
After running the svm 
training with 789 examples
and then
predicting with 400 examples
I get the following error every other time or so

TypeError: Cannot read property 'length' of undefined
    at Object.kernel (/data/node_modules/svm/lib/svm.js:312:23)
    at Object.SVM.marginOne (/data/node_modules/svm/lib/svm.js:199:54)
    at Object.SVM.margins (/data/node_modules/svm/lib/svm.js:217:27)
    at Object.SVM.predict (/data/node_modules/svm/lib/svm.js:225:24)

**Comment by karpathy** [comment]
From a quick look I can't see what would cause the issue and your description is too short. How do you train the SVM? What parameters/kernels are you using? How do you predict?

**Comment by henriksjostrom** [comment]
I'm sorry for taking your time.

This was caused by a nasty bug in my own code that appear only when using a very large dataset.
