### ISSUE TITLE
Install problems under Windows

### ISSUE THREAD

**Issue by RobTS** [karpathy/svmjs#7]
Hi there,

I'd like to use this package as part of my thesis, but can't get it to work on Windows.

I tried it with VS 2010, 2012 and 2013 on Windows 8, but nothing helped. Which system are you able to build it on?

And is it possible to get this to work under Win or will I have to set up Linux on my machine?

Thanks a lot in advance!

Rob

The error message looks as follows: 

> node-svm@1.3.0 install E:_Webstrom Projects\reddscrape\node_modules\node-svm
> node-gyp rebuild

E:_Webstrom Projects\reddscrape\node_modules\node-svm>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  addon.cc
  svm.cpp
  node-svm.cc
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1185): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1185): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1202): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1202): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1215): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1215): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1229): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1229): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1318): warning C4244: 'return' : conversion from 'intptr_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm../../node_modules/nan/nan.h(1318): warning C4244: 'return' : conversion from 'intptr_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(92): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(92): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(95): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(95): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(98): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(98): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(122): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(122): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(125): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(125): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(153): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(155): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(153): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(155): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(179): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(179): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm/node-svm.h(217): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\node-svm.h(217): warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\training-worker.h(31): error C2466: cannot allocate an array of constant size 0 [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
e:_webstrom projects\reddscrape\node_modules\node-svm\src\node-svm\training-worker.h(31): error C2440: 'initializing' : cannot convert from 'int' to 'v8::Local<T>' [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
          with
          [
              T=v8::Value
          ]
          No constructor could take the source type, or constructor overload resolution was ambiguous
..\src\node-svm\node-svm.cc(24): error C2466: cannot allocate an array of constant size 0 [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
..\src\node-svm\node-svm.cc(24): error C2466: cannot allocate an array of constant size 0 [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
..\src\node-svm\node-svm.cc(24): error C2440: 'initializing' : cannot convert from 'int' to 'v8::Local<T>' [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
          with
          [
              T=v8::Value
          ]
          No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Robert.node-gyp\0.10.26\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [E:_Webstrom Projects\reddscrape\node_modules\node-svm\build\addon.vcxproj]
          with
          [
              T=v8::Object
          ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:_Webstrom Projects\reddscrape\node_modules\node-svm
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! node-svm@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-svm@1.3.0 install script.
npm ERR! This is most likely a problem with the node-svm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-svm
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd E:_Webstrom Projects\reddscrape
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:_Webstrom Projects\reddscrape\npm-debug.log
npm ERR! not ok code 0

**Comment by JasonShin** [comment]
Hi, if you are looking for an SVM project in Javascript, check out https://github.com/machinelearnjs/libsvm-ts
